### ISSUE TITLE
How to run an play

### ISSUE THREAD

**Issue by Umairlari12** [rkoeninger/fourchess#1]
How to run and play for 4player chess

**Comment by rkoeninger** [comment]
This project was originally written to use IntelliJ IDEA and there's still an `.idea` folder and `.iml` file in the repo. So you can try building with IntelliJ with the Groovy plugin. Otherwise, I guess you can use the Groovy compiler on the command line.

The main method is in the class `fourchess.FourChess`. It might not work with newer versions of Groovy or the JVM. I don't have any other advice. Good luck!
